### ISSUE TITLE
How to deconvolution on other layers?

### ISSUE THREAD

**Issue by kietikul** [hovinh/DeCNN#1]
Hi Hovinh,
     Thank you so much for your wonderful DeconvNet code. I am wondering how can I take a look on deconvolution image from different layers other than the prediction layer? For example, deconv image from the layer "block1_conv1" of VGG16 model.

**Comment by hovinh** [comment]
Hi kietikul,

You must have noticed the argument `layer_name` here. You can provide the name of the layer of interest and it should output for you.
![image](https://user-images.githubusercontent.com/7614509/130378149-a7f7a501-221e-4200-b84b-b945d7b8890f.png)

For detailed info, please check out this [link](https://github.com/hovinh/DeCNN/blob/master/backprop.py)
![image](https://user-images.githubusercontent.com/7614509/130378209-399fc1ff-d71a-43fe-a8bc-e2b34a8f15b3.png)

Cheers,
Vinh

**Comment by kietikul** [comment]
> Hi kietikul,
> 
> You must have noticed the argument `layer_name` here. You can provide the name of the layer of interest and it should output for you.
> ![image](https://user-images.githubusercontent.com/7614509/130378149-a7f7a501-221e-4200-b84b-b945d7b8890f.png)
> 
> For detailed info, please check out this [link](https://github.com/hovinh/DeCNN/blob/master/backprop.py)
> ![image](https://user-images.githubusercontent.com/7614509/130378209-399fc1ff-d71a-43fe-a8bc-e2b34a8f15b3.png)
> 
> Cheers,
> Vinh

**Comment by kietikul** [comment]
Hi Vinh, 
Thanks a lot for your quick reply. However, I got an error message when I changed the layer name to 'block1_conv1' as follows.

masking = np.zeros(preds.shape)
masking[0, np.argmax(preds)] = 1.
deconvnet = DeconvNet(model=VGG16_net, 
                           **layer_name='block1_conv1',**
                           input_data=x,
                           masking=masking)
heatmap  = deconvnet.compute()
plt.imshow(heatmap[0], cmap='gray'); plt.axis('off'); plt.show()

---------------------------------

Error messages are list below: Is there any way to fix this error, please?

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs, op_def)
   1879   try:
-> 1880     c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
   1881   except errors.InvalidArgumentError as e:

InvalidArgumentError: Dimensions must be equal, but are 64 and 1000 for '{{node mul_1}} = Mul[T=DT_FLOAT](block1_conv1/Relu, mul_1/y)' with input shapes: [?,224,224,64], [1,1000].

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
13 frames
ValueError: Dimensions must be equal, but are 64 and 1000 for '{{node mul_1}} = Mul[T=DT_FLOAT](block1_conv1/Relu, mul_1/y)' with input shapes: [?,224,224,64], [1,1000].

During handling of the above exception, another exception occurred:

NotImplementedError                       Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in __array__(self)
    868         "Cannot convert a symbolic Tensor ({}) to a numpy array."
    869         " This error may indicate that you're trying to pass a Tensor to"
--> 870         " a NumPy call, which is not supported".format(self.name))
    871 
    872   def __len__(self):

NotImplementedError: Cannot convert a symbolic Tensor (block1_conv1/Relu:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

**Comment by hovinh** [comment]
Hi,

Based on the error message, here is my guess:
- *Dimensions must be equal, but are 64 and 1000 ...*:  let's ensure all provided arguments have a valid value, i.e valid shape of the selected layer. My guess is the `masking` value was incorrect. It should take the shape of 'block1_conv1' with zeros value, except for the hidden node you are interested in. Let's see if this fixed before moving on to the next issue.
- *Cannot convert a symbolic Tensor (block1_conv1/Relu:0) to a numpy array*: note that I used the python 3.6 and tensorflow 1.15; even though keras interface stays the same, I'm not sure any unintended error on the backend side or not. I heard there was a huge change when tensorflow stepped up to 2.0. 

Hope this helps.
Vinh
